[server]
headless = true
port = 8888
address = "127.0.0.1"
baseUrlPath = ""
enableCORS = false
enableXsrfProtection = true
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
serverAddress = "127.0.0.1"
serverPort = 8888

# Light theme configuration (default)
[theme]
base = "light"
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"

# Note: Dark theme colors are handled via CSS in main.py
# Streamlit doesn't support runtime theme switching in config.toml,
# so we use CSS for dynamic theme changes based on st.session_state.theme
